name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/checkout@v4
      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Cache outputs
        uses: actions/cache@v4
        with:
          path: |
            .lake
            !.lake/build/doc/HelloTypeSystem.html*
            !.lake/build/doc/HelloTypeSystem/**/*
          key: deps-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lake-manifest.json') }}-${{ github.sha }}
          restore-keys: |
            deps-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lake-manifest.json') }}
            deps-${{ runner.os }}-${{ hashFiles('lean-toolchain') }}
      - name: Build
        run: |
          lake build
      - name: Generate docs
        run: |
          lake -R -Kenv=dev update
          lake -R -Kenv=dev build HelloTypeSystem:docs
      - name: Upload Pages artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".lake/build/doc"
      - id: deployment
        name: Deploy docs to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: actions/deploy-pages@v4
    permissions:
      contents: read
      pages: write
      id-token: write
